### PR TITLE
multiple fixes

### PR DESCRIPTION
**Pull request by liberize**
1. auto paste on select
2. display multiple lines as one line
3. fix plugin thread preventing main program from exiting
4. increase max history count, fix new record not appending after limit reached

there remains 2 problems which are related to flow launcher:
1. results not refreshing after press hot key (fixed by https://github.com/Flow-Launcher/Flow.Launcher/issues/701)
2. selected entries are pinned to top, even after new text is copied (related to https://github.com/Flow-Launcher/Flow.Launcher/issues/768)

### CODE REVIEW

**Comment by taooceros** [comment]
> selected entries are pinned to top, even after new text is copied (related to Keep the order of the results Flow-Launcher/Flow.Launcher#768)

Maybe you can assign a score to the results based on the time they created?

**Comment by taooceros** [comment]
Also, it looks like the repo owner has not responded for a long time. Maybe you can create release in your fork and migrate the clipboard plugin link to your fork until the author respond.

**Comment by taooceros** [comment]
> fix plugin thread preventing main program from exiting

For this, could you also add disposable for clipboard plugin? Flow will now dispose all plugin when exit.

**Comment by liberize** [comment]
> > selected entries are pinned to top, even after new text is copied (related to Keep the order of the results [Flow-Launcher/Flow.Launcher#768](https://github.com/Flow-Launcher/Flow.Launcher/issues/768))
> 
> Maybe you can assign a score to the results based on the time they created?

it looks like the score of selected results are promoted:

https://github.com/Flow-Launcher/Flow.Launcher/blob/e69b4541390b1403612bbf34cb6d0eb9302371a1/Flow.Launcher/ViewModel/MainViewModel.cs#L800

does this happen if i specify score for each entry?

**Comment by liberize** [comment]
it seems the search functionality is broken too, because `SecondToEndSearch` doesn't contain first query word (exclude keyword) now
https://github.com/Flow-Launcher/Flow.Launcher/issues/680

**Comment by liberize** [comment]
> > fix plugin thread preventing main program from exiting
> 
> For this, could you also add disposable for clipboard plugin? Flow will now dispose all plugin when exit.

I added `IDisposable` interface to `ClipboardHistory` class, but `Dispose` method is not called.
The Flow.Launcher.Plugin package version is 1.3.0. Do i need to update it or not?
The latest 2.0.0 version depends on .net 5.0, while 1.3.0 depends on .net core 3.1.

Anyway, the not-exiting problem seems to be already fixed without Dispose.

**Comment by liberize** [comment]
> > > selected entries are pinned to top, even after new text is copied (related to Keep the order of the results [Flow-Launcher/Flow.Launcher#768](https://github.com/Flow-Launcher/Flow.Launcher/issues/768))
> > 
> > 
> > Maybe you can assign a score to the results based on the time they created?
> 
> it looks like the score of selected results are promoted:
> 
> https://github.com/Flow-Launcher/Flow.Launcher/blob/e69b4541390b1403612bbf34cb6d0eb9302371a1/Flow.Launcher/ViewModel/MainViewModel.cs#L800
> 
> does this happen if i specify score for each entry?

I made a workaround to set score with a big step, like 1000, 2000, 3000...
should work in most cases even after scores are promoted by history selection.

**Comment by taooceros** [comment]
> > > fix plugin thread preventing main program from exiting
> > 
> > For this, could you also add disposable for clipboard plugin? Flow will now dispose all plugin when exit.
> 
> I added `IDisposable` interface to `ClipboardHistory` class, but `Dispose` method is not called.
> The Flow.Launcher.Plugin package version is 1.3.0. Do i need to update it or not?
> The latest 2.0.0 version depends on .net 5.0, while 1.3.0 depends on .net core 3.1.
> 
> Anyway, the not-exiting problem seems to be already fixed without Dispose.

Why not? Flow has updated to .net 5 in 1.8+.
Though I think dispose should work even if we does not update. Let me take a check later.

**Comment by taooceros** [comment]
> it seems the search functionality is broken too, because `SecondToEndSearch` doesn't contain first query word (exclude keyword) now
> https://github.com/Flow-Launcher/Flow.Launcher/issues/680

Hm I don't think it contains the first query word even at before....

**Comment by taooceros** [comment]
> I made a workaround to set score with a big step, like 1000, 2000, 3000...
should work in most cases even after scores are promoted by history selection.

The bump is 5 per selected. So I don't think it needs that large score. 🤣

**Pull request closed without merging**
